apiVersion: apps/v1    #Este es controlador se le coloca apps
kind: StatefulSet
metadata:
  name: bdmonedas-sfs
spec:
  serviceName: "bdmonedas-servicio"
  replicas: 1
  selector:
    matchLabels:
      app: bdmonedas 
  template:
    metadata:
      labels:
        app: bdmonedas
    spec:
      containers:
        - name: bdmonedas  # <-- Aquí empieza la definición del único contenedor
          image: postgres:16
          ports:
            - containerPort: 5433 # <-- El mismo de targerPort del servicio.
          env:  # <-- Esta sección debe estar indentada al mismo nivel que 'ports', 'image', 'name'
            - name: POSTGRES_DB
              value: monedas
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bdmonedas-secretos
                  key: BDMONEDAS_PASSWORD
          volumeMounts:
            - name: storage-bdmonedas
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: storage-bdmonedas
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
 
