apiVersion: v1
kind: PersistentVolume
metadata:
  name: bdmonedas-pv
spec: #Especificaciones
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres"
  persistentVolumeReclaimPolicy: Delete