apiVersion: apps/v1    #Este es controlador es el analogo a StateFulSet en la BD
kind: Deployment
metadata:
  name: apimonedas-deployment-tt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apimonedas-tt
  template:
    metadata:
      labels:
        app: apimonedas-tt
    spec:
      containers:
        - name: apimonedas
          image: moxow/api_monedas_tt # Repositorio Docker
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: apimonedas-configmap-tt  # nombre del configMap api
            - secretRef:
                name: bdmonedas-secretos # nombre del archivo de secretos BD